sudo: required
services:
  - docker

before_install:
  - docker build -t kumargaurav1013/docker-react -f Dockerfile.dev .

script:
  -docker run kumargaurav1013/docker-react npm run test -- --coverage 